import type { WorkItem } from './types'

/** Расширенный мок-реестр: прототип Nodus + сущности HR Helper (маршруты fe_migration). */
export const MOCK_WORK_ITEMS: WorkItem[] = [
  {
    id: 'CAND-001',
    domain: 'candidate',
    title: 'Иван Сидоров — Frontend Dev',
    status: 'Интервью',
    assignee: 'АК',
    priority: 'Высокий',
    date: '01 апр',
    dueAt: '2026-04-01',
    showInFooter: true,
    tags: ['React', 'TS'],
    description:
      'Опыт 4 года, стек React + TypeScript. Прошёл первый скрин, назначено техинтервью.',
    relatedItems: ['VAC-003', 'SPEC-001'],
    menuContext: 'ATS | Talent Pool',
    appLinks: [
      { label: 'ATS', href: '/ats/vacancy/1/candidate/1' },
      { label: 'Вакансии', href: '/vacancies' },
    ],
  },
  {
    id: 'CAND-002',
    domain: 'candidate',
    title: 'Мария Коваль — Backend Python',
    status: 'Скрин',
    assignee: 'МВ',
    priority: 'Средний',
    date: '02 апр',
    dueAt: '2026-04-02',
    tags: ['Python', 'Django'],
    description: '5 лет опыта Python/Django, работает в стартапе. Ищет удалёнку.',
    relatedItems: ['VAC-002'],
    menuContext: 'Huntflow → отклики',
    appLinks: [{ label: 'Инвайты', href: '/invites' }],
  },
  {
    id: 'CAND-003',
    domain: 'candidate',
    title: 'Дмитрий Лебедев — DevOps',
    status: 'Оффер',
    assignee: 'АК',
    priority: 'Критичный',
    date: '31 мар',
    dueAt: '2026-03-31',
    tags: ['k8s', 'AWS'],
    description: 'Финальный кандидат. Ожидает оффер до 3 апреля.',
    relatedItems: ['VAC-004'],
    appLinks: [
      { label: 'Шаблон оффера', href: '/company-settings/recruiting/offer-template' },
      { label: 'Бенчмарки', href: '/company-settings/finance/benchmarks' },
    ],
  },
  {
    id: 'PROJ-001',
    domain: 'project',
    title: 'Автоматизация HR-воронки',
    status: 'В работе',
    assignee: 'АК',
    priority: 'Высокий',
    date: '15 апр',
    dueAt: '2026-04-15',
    showInFooter: true,
    tags: ['n8n', 'Chrome'],
    description: 'Интеграция LinkedIn → Huntflow через браузерное расширение и n8n webhooks.',
    relatedItems: ['CAND-001', 'CAND-002'],
    appLinks: [
      { label: 'Исходящие интеграции', href: '/settings/outbound-integrations' },
      { label: 'Workflow', href: '/workflow' },
    ],
  },
  {
    id: 'PROJ-002',
    domain: 'project',
    title: 'Редизайн портала вакансий',
    status: 'Планирование',
    assignee: 'МВ',
    priority: 'Средний',
    date: '30 апр',
    dueAt: '2026-04-30',
    tags: ['React', 'UI'],
    description: 'Обновление frontend портала. Новый дизайн, мобильная адаптация.',
    relatedItems: ['VAC-001'],
    appLinks: [{ label: 'Вакансии', href: '/vacancies' }],
  },
  {
    id: 'EVENT-001',
    domain: 'event',
    title: 'Техинтервью: Иван Сидоров',
    status: 'Новый',
    assignee: 'АК',
    priority: 'Высокий',
    date: '02 апр',
    dueAt: '2026-04-02',
    showInFooter: true,
    tags: ['Interview'],
    description: 'Техническое интервью с Frontend кандидатом. Google Meet, 60 минут.',
    relatedItems: ['CAND-001'],
    appLinks: [
      { label: 'Календарь', href: '/calendar' },
      { label: 'Интервьюеры', href: '/interviewers' },
    ],
  },
  {
    id: 'EVENT-002',
    domain: 'event',
    title: 'Митинг по Q2 рекрутинг-плану',
    status: 'Новый',
    assignee: 'АК',
    priority: 'Средний',
    date: '03 апр',
    tags: ['Planning'],
    description: 'Обсуждение планов найма на Q2, пересмотр приоритетов.',
    relatedItems: ['PROJ-001'],
    appLinks: [{ label: 'План найма', href: '/reporting/hiring-plan' }],
  },
  {
    id: 'EVENT-003',
    domain: 'event',
    title: 'Демо: HR Extension v2.1',
    status: 'Готово',
    assignee: 'АК',
    priority: 'Средний',
    date: '29 мар',
    dueAt: '2026-03-29',
    tags: ['Demo'],
    description: 'Демонстрация новой версии расширения команде.',
    relatedItems: ['PROJ-001'],
    appLinks: [{ label: 'Внутренний портал', href: '/internal-site' }],
  },
  {
    id: 'MEET-001',
    domain: 'meet',
    title: 'Синк: статусы инвайтов и SLA',
    status: 'Новый',
    assignee: 'АК',
    priority: 'Высокий',
    date: '04 апр',
    dueAt: '2026-04-04',
    showInFooter: true,
    tags: ['Мит', 'Рекрутинг'],
    description: 'Внутренний мит: короткий разбор висящих инвайтов и нарушений SLA по вакансиям.',
    relatedItems: ['HR-REQ-001', 'INT-001'],
    menuContext: 'Внутренние миты',
    appLinks: [
      { label: 'Миты — домашняя', href: '/meet' },
      { label: 'Комната (мок)', href: '/meet/room' },
    ],
  },
  {
    id: 'MEET-002',
    domain: 'meet',
    title: 'Разбор Q1 — демо записей',
    status: 'Планирование',
    assignee: 'МВ',
    priority: 'Низкий',
    date: '10 апр',
    dueAt: '2026-04-10',
    tags: ['Архив', 'Обучение'],
    description: 'Просмотр записей из архива митов для онбординга новых интервьюеров.',
    relatedItems: [],
    appLinks: [{ label: 'Архив митов', href: '/meet/archive' }],
  },
  {
    id: 'WIKI-001',
    domain: 'wiki',
    title: 'Процесс онбординга кандидатов',
    status: 'Готово',
    assignee: 'МВ',
    priority: 'Средний',
    date: '15 мар',
    dueAt: '2026-03-15',
    showInFooter: true,
    tags: ['Process'],
    description: 'Полный гайд: от первого контакта до выхода на работу.',
    relatedItems: ['CAND-001', 'CAND-002'],
    appLinks: [{ label: 'Wiki (legacy)', href: '/wiki' }, { label: 'Wiki New', href: '/wiki-new' }],
  },
  {
    id: 'WIKI-002',
    domain: 'wiki',
    title: 'Шаблон технического интервью',
    status: 'На ревью',
    assignee: 'АК',
    priority: 'Средний',
    date: '20 мар',
    dueAt: '2026-03-20',
    tags: ['Template'],
    description: 'Стандартизированный шаблон для проведения технических собеседований.',
    relatedItems: [],
    appLinks: [{ label: 'Ответы кандидатам', href: '/candidate-responses' }],
  },
  {
    id: 'SPEC-001',
    domain: 'specialist',
    title: 'Алексей Михайлов — FullStack',
    status: 'Новый',
    assignee: 'АК',
    priority: 'Средний',
    date: '05 апр',
    dueAt: '2026-04-05',
    tags: ['React', 'Go'],
    description: 'Проверенный специалист, работал в прошлых проектах. Возможный кандидат для VAC-001.',
    relatedItems: ['VAC-001'],
    appLinks: [{ label: 'Специализации', href: '/specializations' }],
  },
  {
    id: 'VAC-001',
    domain: 'vacancy',
    title: 'Senior Frontend Developer',
    status: 'В работе',
    assignee: 'АК',
    priority: 'Критичный',
    date: '15 апр',
    dueAt: '2026-04-15',
    showInFooter: true,
    tags: ['Frontend'],
    description:
      'Нужен сильный frontend с опытом React. 4+ лет, TSX, хорошее знание архитектурных паттернов.',
    relatedItems: ['CAND-001', 'SPEC-001'],
    appLinks: [{ label: 'Вакансии', href: '/vacancies' }, { label: 'План найма', href: '/reporting/hiring-plan' }],
  },
  {
    id: 'VAC-002',
    domain: 'vacancy',
    title: 'Backend Python Engineer',
    status: 'В работе',
    assignee: 'МВ',
    priority: 'Высокий',
    date: '30 апр',
    dueAt: '2026-04-30',
    tags: ['Backend'],
    description: 'Python/Django бэкенд разработчик. Опыт от 3 лет, знание REST API.',
    relatedItems: ['CAND-002'],
    appLinks: [{ label: 'SLA вакансий', href: '/company-settings/sla' }],
  },
  {
    id: 'VAC-003',
    domain: 'vacancy',
    title: 'React Native Developer',
    status: 'Планирование',
    assignee: 'АК',
    priority: 'Средний',
    date: '01 мая',
    dueAt: '2026-05-01',
    tags: ['Mobile'],
    description: 'Мобильный разработчик для нового продукта. React Native, опыт с Expo.',
    relatedItems: [],
    appLinks: [{ label: 'Вакансии', href: '/vacancies' }],
  },
  {
    id: 'VAC-004',
    domain: 'vacancy',
    title: 'DevOps / SRE Engineer',
    status: 'Оффер',
    assignee: 'АК',
    priority: 'Критичный',
    date: '31 мар',
    dueAt: '2026-03-31',
    tags: ['DevOps'],
    description: 'DevOps с опытом Kubernetes, AWS/GCP, CI/CD пайплайны.',
    relatedItems: ['CAND-003'],
    appLinks: [{ label: 'Зарплатные вилки', href: '/vacancies/salary-ranges' }],
  },
  {
    id: 'HR-REQ-001',
    domain: 'hiring_request',
    title: 'Заявка: Support Engineer (L2)',
    status: 'В работе',
    assignee: 'МВ',
    priority: 'Высокий',
    date: '28 мар',
    dueAt: '2026-03-28',
    tags: ['Заявка', 'SLA'],
    description: 'Расширение саппорта; согласовать грейд и вилку с финансами до открытия вакансии.',
    relatedItems: ['VAC-002'],
    menuContext: 'Заявки на найм',
    appLinks: [
      { label: 'Заявки на найм', href: '/hiring-requests' },
      { label: 'Годовой план', href: '/reporting/hiring-plan/yearly' },
    ],
  },
  {
    id: 'HR-REQ-002',
    domain: 'hiring_request',
    title: 'Заявка: Data Analyst (продукт)',
    status: 'Новый',
    assignee: 'АК',
    priority: 'Средний',
    date: '08 апр',
    dueAt: '2026-04-08',
    tags: ['Analytics', 'Продукт'],
    description: 'Новая роль под продуктовую аналитику; черновик в HR Helper.',
    relatedItems: [],
    appLinks: [{ label: 'Отчёты', href: '/reporting' }],
  },
  {
    id: 'INT-001',
    domain: 'integration',
    title: 'Huntflow ↔ n8n: webhooks вакансий',
    status: 'В работе',
    assignee: 'АК',
    priority: 'Высокий',
    date: '12 апр',
    dueAt: '2026-04-12',
    showInFooter: true,
    tags: ['Huntflow', 'n8n'],
    description: 'Синхронизация статусов вакансий и кандидатов; ретраи и алерты в Workflow.',
    relatedItems: ['PROJ-001'],
    menuContext: 'Интеграции компании',
    appLinks: [
      { label: 'Интеграции (настройки)', href: '/company-settings/integrations' },
      { label: 'Шлюзы', href: '/settings/gateways' },
    ],
  },
  {
    id: 'INT-002',
    domain: 'integration',
    title: 'Telegram-бот: уведомления интервью',
    status: 'На ревью',
    assignee: 'МВ',
    priority: 'Средний',
    date: '06 апр',
    dueAt: '2026-04-06',
    tags: ['Telegram', 'Calendar'],
    description: 'Мок: бот шлёт напоминания за 15 мин до слота из календаря.',
    relatedItems: ['EVENT-001'],
    appLinks: [{ label: 'Telegram', href: '/telegram' }, { label: 'Календарь', href: '/calendar' }],
  },
  {
    id: 'RPT-001',
    domain: 'report',
    title: 'Еженедельный отчёт по воронке',
    status: 'Готово',
    assignee: 'АК',
    priority: 'Низкий',
    date: '30 мар',
    dueAt: '2026-03-30',
    tags: ['Отчёт', 'Рекрутинг'],
    description: 'Сводка этапов, конверсии и узкие места; выгрузка для руководства.',
    relatedItems: ['VAC-001', 'VAC-004'],
    appLinks: [
      { label: 'Отчёты по подбору', href: '/reporting' },
      { label: 'Отчёт компании', href: '/reporting/company' },
    ],
  },
  {
    id: 'RPT-002',
    domain: 'report',
    title: 'Бенчмарки: сверка вилок Q2',
    status: 'В работе',
    assignee: 'МВ',
    priority: 'Средний',
    date: '18 апр',
    dueAt: '2026-04-18',
    tags: ['Финансы', 'Бенчмарки'],
    description: 'Подготовка среза бенчмарков перед пересмотром офферной политики.',
    relatedItems: ['CAND-003'],
    appLinks: [{ label: 'Бенчмарки', href: '/finance/benchmarks/all' }],
  },
  {
    id: 'TASK-039',
    domain: 'task',
    title: 'Проверить права на модуль «Обучение»',
    status: 'Новый',
    assignee: 'АК',
    priority: 'Низкий',
    date: '07 апр',
    dueAt: '2026-04-07',
    showInFooter: true,
    tags: ['Настройки', 'RBAC'],
    description: 'Убедиться, что гостям не виден раздел обучения после последнего деплоя.',
    relatedItems: [],
    menuContext: 'Настройки безопасности',
    appLinks: [
      { label: 'Роли', href: '/settings/roles' },
      { label: 'Модули', href: '/settings/modules' },
    ],
  },
  {
    id: 'COMP-001',
    domain: 'company',
    title: 'Обновить политику удалённой работы (HR)',
    status: 'Планирование',
    assignee: 'МВ',
    priority: 'Средний',
    date: '20 апр',
    dueAt: '2026-04-20',
    tags: ['Политика'],
    description: 'Согласовать формулировки с legal и выложить в вики.',
    relatedItems: ['WIKI-001'],
    appLinks: [{ label: 'Настройки компании', href: '/company-settings' }],
  },
]
