import type { RbacGroupNode, RbacRole, RbacSecurityUser } from '@/features/rbac-admin/types'

const COLORS = [
  '#c0392b',
  '#2563eb',
  '#16a34a',
  '#d97706',
  '#7c3aed',
  '#0891b2',
  '#be185d',
  '#065f46',
] as const

export const MOCK_RBAC_ROLES_BASE: RbacRole[] = [
  {
    id: 'admin',
    slug: 'admin',
    displayName: 'Администратор',
    description: 'Полный доступ ко всем модулям системы',
    isSystem: true,
    isDefault: false,
    priority: 100,
    color: '#c0392b',
    userCount: 3,
    permissionCount: 48,
    parentRoleId: null,
  },
  {
    id: 'editor',
    slug: 'editor',
    displayName: 'Редактор',
    description: 'Создание и редактирование контента; без удаления критичных сущностей',
    isSystem: false,
    isDefault: false,
    priority: 60,
    color: '#2563eb',
    userCount: 22,
    permissionCount: 18,
    parentRoleId: 'viewer',
  },
  {
    id: 'senior_editor',
    slug: 'senior_editor',
    displayName: 'Старший редактор',
    description: 'Расширенные права редактора внутри команды контента',
    isSystem: false,
    isDefault: false,
    priority: 58,
    color: '#1e40af',
    userCount: 0,
    permissionCount: 0,
    parentRoleId: 'editor',
  },
  {
    id: 'analyst',
    slug: 'analyst',
    displayName: 'Аналитик',
    description: 'Просмотр и экспорт данных, отчёты',
    isSystem: false,
    isDefault: false,
    priority: 50,
    color: '#7c3aed',
    userCount: 15,
    permissionCount: 12,
    parentRoleId: null,
  },
  {
    id: 'moderator',
    slug: 'moderator',
    displayName: 'Модератор',
    description: 'Модерация пользовательского контента',
    isSystem: false,
    isDefault: false,
    priority: 40,
    color: '#0891b2',
    userCount: 8,
    permissionCount: 10,
    parentRoleId: 'viewer',
  },
  {
    id: 'viewer',
    slug: 'viewer',
    displayName: 'Наблюдатель',
    description: 'Только просмотр без права изменений',
    isSystem: true,
    isDefault: true,
    priority: 10,
    color: '#6b7280',
    userCount: 199,
    permissionCount: 6,
    parentRoleId: null,
  },
]

export const MOCK_RBAC_USERS: RbacSecurityUser[] = [
  {
    id: 'u1',
    firstName: 'Алексей',
    lastName: 'Воронов',
    email: 'a.voronov@company.ru',
    username: 'a.voronov',
    status: 'active',
    roleLabels: ['Администратор'],
    groupLabels: ['IT'],
    mfaEnabled: true,
    lastLoginLabel: '2 мин назад',
    avatarColor: COLORS[0],
  },
  {
    id: 'u2',
    firstName: 'Мария',
    lastName: 'Семёнова',
    email: 'm.semenova@company.ru',
    username: 'm.semenova',
    status: 'active',
    roleLabels: ['Редактор', 'Аналитик'],
    groupLabels: ['Маркетинг'],
    mfaEnabled: true,
    lastLoginLabel: '1 ч назад',
    avatarColor: COLORS[1],
  },
  {
    id: 'u3',
    firstName: 'Дмитрий',
    lastName: 'Козлов',
    email: 'd.kozlov@company.ru',
    username: 'd.kozlov',
    status: 'active',
    roleLabels: ['Редактор'],
    groupLabels: ['Разработка'],
    mfaEnabled: false,
    lastLoginLabel: '3 ч назад',
    avatarColor: COLORS[2],
  },
  {
    id: 'u4',
    firstName: 'Анна',
    lastName: 'Фёдорова',
    email: 'a.fedorova@company.ru',
    username: 'a.fedorova',
    status: 'blocked',
    roleLabels: ['Наблюдатель'],
    groupLabels: ['HR'],
    mfaEnabled: false,
    lastLoginLabel: '14 дн назад',
    avatarColor: COLORS[3],
  },
  {
    id: 'u5',
    firstName: 'Сергей',
    lastName: 'Новиков',
    email: 's.novikov@company.ru',
    username: 's.novikov',
    status: 'active',
    roleLabels: ['Аналитик'],
    groupLabels: ['Финансы'],
    mfaEnabled: true,
    lastLoginLabel: 'вчера',
    avatarColor: COLORS[4],
  },
  {
    id: 'u6',
    firstName: 'Екатерина',
    lastName: 'Морозова',
    email: 'e.morozova@company.ru',
    username: 'e.morozova',
    status: 'pending',
    roleLabels: ['Наблюдатель'],
    groupLabels: ['Маркетинг'],
    mfaEnabled: false,
    lastLoginLabel: '—',
    avatarColor: COLORS[5],
  },
  {
    id: 'u7',
    firstName: 'Игорь',
    lastName: 'Белов',
    email: 'i.belov@company.ru',
    username: 'i.belov',
    status: 'active',
    roleLabels: ['Модератор'],
    groupLabels: ['Разработка'],
    mfaEnabled: true,
    lastLoginLabel: '5 мин назад',
    avatarColor: COLORS[6],
  },
  {
    id: 'u8',
    firstName: 'Наталья',
    lastName: 'Кузнецова',
    email: 'n.kuznetsova@company.ru',
    username: 'n.kuznetsova',
    status: 'active',
    roleLabels: ['Редактор'],
    groupLabels: ['Разработка', 'IT'],
    mfaEnabled: false,
    lastLoginLabel: '2 ч назад',
    avatarColor: COLORS[7],
  },
  {
    id: 'u9',
    firstName: 'Павел',
    lastName: 'Орлов',
    email: 'p.orlov@company.ru',
    username: 'p.orlov',
    status: 'active',
    roleLabels: ['Аналитик', 'Наблюдатель'],
    groupLabels: ['Финансы'],
    mfaEnabled: true,
    lastLoginLabel: '30 мин назад',
    avatarColor: COLORS[1],
  },
  {
    id: 'u10',
    firstName: 'Татьяна',
    lastName: 'Лебедева',
    email: 't.lebedeva@company.ru',
    username: 't.lebedeva',
    status: 'blocked',
    roleLabels: ['Наблюдатель'],
    groupLabels: ['HR'],
    mfaEnabled: false,
    lastLoginLabel: '32 дн назад',
    avatarColor: COLORS[2],
  },
  {
    id: 'u11',
    firstName: 'Олег',
    lastName: 'Смирнов',
    email: 'o.smirnov@company.ru',
    username: 'o.smirnov',
    status: 'active',
    roleLabels: ['Редактор'],
    groupLabels: ['Фронтенд'],
    mfaEnabled: true,
    lastLoginLabel: 'сегодня',
    avatarColor: COLORS[3],
  },
]

export const MOCK_GROUP_TREE: RbacGroupNode = {
  id: 'root',
  name: 'Компания',
  iconKey: 'building',
  type: 'organizational',
  inheritedRoleLabels: [],
  memberCount: 247,
  children: [
    {
      id: 'dev',
      name: 'Разработка',
      iconKey: 'code',
      type: 'organizational',
      inheritedRoleLabels: ['Редактор'],
      memberCount: 28,
      children: [
        {
          id: 'frontend',
          name: 'Фронтенд',
          iconKey: 'layout',
          type: 'functional',
          inheritedRoleLabels: ['Редактор'],
          memberCount: 11,
          children: [],
        },
        {
          id: 'backend',
          name: 'Бэкенд',
          iconKey: 'server',
          type: 'functional',
          inheritedRoleLabels: ['Редактор'],
          memberCount: 12,
          children: [],
        },
        {
          id: 'devops',
          name: 'DevOps',
          iconKey: 'container',
          type: 'functional',
          inheritedRoleLabels: ['Администратор'],
          memberCount: 6,
          children: [],
        },
      ],
    },
    {
      id: 'marketing',
      name: 'Маркетинг',
      iconKey: 'megaphone',
      type: 'organizational',
      inheritedRoleLabels: ['Редактор'],
      memberCount: 18,
      children: [
        {
          id: 'content',
          name: 'Контент',
          iconKey: 'file',
          type: 'functional',
          inheritedRoleLabels: ['Редактор'],
          memberCount: 8,
          children: [],
        },
        {
          id: 'analytics_mkt',
          name: 'Аналитика',
          iconKey: 'chart',
          type: 'functional',
          inheritedRoleLabels: ['Аналитик'],
          memberCount: 10,
          children: [],
        },
      ],
    },
    {
      id: 'finance',
      name: 'Финансы',
      iconKey: 'landmark',
      type: 'organizational',
      inheritedRoleLabels: ['Аналитик'],
      memberCount: 12,
      children: [],
    },
    {
      id: 'hr',
      name: 'HR',
      iconKey: 'users',
      type: 'organizational',
      inheritedRoleLabels: ['Наблюдатель'],
      memberCount: 7,
      children: [],
    },
    {
      id: 'it',
      name: 'IT',
      iconKey: 'cpu',
      type: 'organizational',
      inheritedRoleLabels: ['Администратор'],
      memberCount: 5,
      children: [],
    },
  ],
}

export const ALL_ROLE_LABELS_FOR_FILTER: string[] = [
  'Администратор',
  'Редактор',
  'Старший редактор',
  'Аналитик',
  'Наблюдатель',
  'Модератор',
]
