import type { OutboundDeliveryLogEntry, OutboundEventDefinition } from '@/features/system-settings/types'

/** Базовый реестр исходящих событий (мок); метаданные из кода, доставку можно отключать per-event. */
export const OUTBOUND_EVENT_CATALOG_DEFAULTS: OutboundEventDefinition[] = [
  {
    id: 'evt-cand-stage',
    eventKey: 'candidate.stage_changed',
    category: 'Рекрутинг',
    title: 'Смена этапа кандидата',
    description: 'Переход воронки, владелец этапа, SLA.',
    payloadSchemaVersion: '2025.2',
    samplePayloadPreview: '{"event":"candidate.stage_changed","candidateId":"…","vacancyId":"…","stage":"interview","at":"ISO-8601"}',
    deliveryEnabled: true,
    dataClassification: 'confidential',
  },
  {
    id: 'evt-cand-created',
    eventKey: 'candidate.created',
    category: 'Рекрутинг',
    title: 'Создан профиль кандидата',
    description: 'Источник, реферер, дубликаты.',
    payloadSchemaVersion: '2025.2',
    samplePayloadPreview: '{"event":"candidate.created","candidateId":"…","source":"hh","at":"ISO-8601"}',
    deliveryEnabled: true,
    dataClassification: 'confidential',
  },
  {
    id: 'evt-vac-status',
    eventKey: 'vacancy.status_changed',
    category: 'Рекрутинг',
    title: 'Статус вакансии',
    description: 'Открыта, на паузе, закрыта, архив.',
    payloadSchemaVersion: '2025.1',
    samplePayloadPreview: '{"event":"vacancy.status_changed","vacancyId":"…","status":"open","at":"ISO-8601"}',
    deliveryEnabled: true,
    dataClassification: 'internal',
  },
  {
    id: 'evt-vac-published',
    eventKey: 'vacancy.published',
    category: 'Рекрутинг',
    title: 'Публикация вакансии',
    description: 'Каналы публикации, внешние ID.',
    payloadSchemaVersion: '2025.1',
    samplePayloadPreview: '{"event":"vacancy.published","vacancyId":"…","channels":["hh","career_site"]}',
    deliveryEnabled: true,
    dataClassification: 'internal',
  },
  {
    id: 'evt-emp-hired',
    eventKey: 'employee.hired',
    category: 'Сотрудники',
    title: 'Выход сотрудника',
    description: 'Дата выхода, подразделение, должность.',
    payloadSchemaVersion: '2025.2',
    samplePayloadPreview: '{"event":"employee.hired","employeeId":"…","startDate":"…","position":"…"}',
    deliveryEnabled: true,
    dataClassification: 'confidential',
  },
  {
    id: 'evt-emp-term',
    eventKey: 'employee.terminated',
    category: 'Сотрудники',
    title: 'Увольнение',
    description: 'Причина, дата последнего дня (без PII в базовом контуре).',
    payloadSchemaVersion: '2025.2',
    samplePayloadPreview: '{"event":"employee.terminated","employeeId":"…","lastDay":"…","reasonCode":"VOLUNTARY"}',
    deliveryEnabled: false,
    dataClassification: 'restricted',
  },
  {
    id: 'evt-learn-done',
    eventKey: 'learning.course_completed',
    category: 'L&D',
    title: 'Курс пройден',
    description: 'Прогресс, сертификат, баллы.',
    payloadSchemaVersion: '2024.3',
    samplePayloadPreview: '{"event":"learning.course_completed","userId":"…","courseId":"…","score":92}',
    deliveryEnabled: true,
    dataClassification: 'internal',
  },
  {
    id: 'evt-perf-review',
    eventKey: 'performance.review_submitted',
    category: 'Эффективность',
    title: 'Отправлена оценка',
    description: 'Цикл, респонденты, агрегированный статус (без ответов).',
    payloadSchemaVersion: '2025.1',
    samplePayloadPreview: '{"event":"performance.review_submitted","cycleId":"…","subjectId":"…","status":"submitted"}',
    deliveryEnabled: true,
    dataClassification: 'confidential',
  },
  {
    id: 'evt-audit-fail',
    eventKey: 'audit.login_failed',
    category: 'Безопасность',
    title: 'Неудачный вход',
    description: 'IP, user agent, метка времени (для SIEM).',
    payloadSchemaVersion: '2025.1',
    samplePayloadPreview: '{"event":"audit.login_failed","login":"…","ip":"…","at":"ISO-8601"}',
    deliveryEnabled: true,
    dataClassification: 'internal',
  },
  {
    id: 'evt-integ-err',
    eventKey: 'integration.api_error',
    category: 'Интеграции',
    title: 'Ошибка внешнего API',
    description: 'Код интеграции, HTTP-статус, корреляционный id.',
    payloadSchemaVersion: '2025.1',
    samplePayloadPreview: '{"event":"integration.api_error","integrationId":"huntflow","status":502,"traceId":"…"}',
    deliveryEnabled: true,
    dataClassification: 'internal',
  },
  {
    id: 'evt-idp-goal',
    eventKey: 'idp.goal_completed',
    category: 'L&D',
    title: 'Цель ИПР достигнута',
    description: 'Цель, план развития, связь с компетенциями.',
    payloadSchemaVersion: '2024.3',
    samplePayloadPreview: '{"event":"idp.goal_completed","planId":"…","goalId":"…","userId":"…"}',
    deliveryEnabled: true,
    dataClassification: 'internal',
  },
  {
    id: 'evt-ts-approved',
    eventKey: 'timesheet.approved',
    category: 'HROps',
    title: 'Табель утверждён',
    description: 'Период, менеджер, сумма часов.',
    payloadSchemaVersion: '2025.1',
    samplePayloadPreview: '{"event":"timesheet.approved","period":"2026-03","employeeId":"…","hours":168}',
    deliveryEnabled: false,
    dataClassification: 'confidential',
  },
]

export function buildOutboundEventCatalog(overrides: Record<string, boolean>): OutboundEventDefinition[] {
  return OUTBOUND_EVENT_CATALOG_DEFAULTS.map((d) => ({
    ...d,
    deliveryEnabled:
      typeof overrides[d.id] === 'boolean' ? overrides[d.id]! : d.deliveryEnabled,
  }))
}

/** Статичный журнал для вкладки «Доставка» (не персистится). */
export const OUTBOUND_DELIVERY_LOG_MOCK: OutboundDeliveryLogEntry[] = [
  {
    id: 'log-1',
    at: '2026-03-30T08:12:01.000Z',
    webhookId: 'wh-1',
    webhookName: 'Корпоративный n8n',
    eventKey: 'candidate.stage_changed',
    status: 'delivered',
    httpStatus: 200,
    durationMs: 142,
  },
  {
    id: 'log-2',
    at: '2026-03-30T08:05:44.000Z',
    webhookId: 'wh-1',
    webhookName: 'Корпоративный n8n',
    eventKey: 'vacancy.status_changed',
    status: 'delivered',
    httpStatus: 200,
    durationMs: 89,
  },
  {
    id: 'log-3',
    at: '2026-03-29T21:18:33.000Z',
    webhookId: 'wh-2',
    webhookName: 'Резерв SIEM (алерты безопасности)',
    eventKey: 'audit.login_failed',
    status: 'failed',
    httpStatus: 503,
    durationMs: 30001,
  },
  {
    id: 'log-4',
    at: '2026-03-29T21:19:05.000Z',
    webhookId: 'wh-2',
    webhookName: 'Резерв SIEM (алерты безопасности)',
    eventKey: 'audit.login_failed',
    status: 'delivered',
    httpStatus: 202,
    durationMs: 210,
  },
  {
    id: 'log-5',
    at: '2026-03-29T14:00:00.000Z',
    webhookId: 'wh-1',
    webhookName: 'Корпоративный n8n',
    eventKey: 'learning.course_completed',
    status: 'pending',
  },
]
