import type { TaskItem } from '@/features/tasks/types'

export const MOCK_TASKS: TaskItem[] = [
  {
    id: 't-rec-1',
    title: 'Согласовать оффер (Middle Frontend)',
    summary:
      'После техинтервью: вилка, даты выхода, условия. Свериться с бенчмарками и политикой оффера в настройках рекрутинга.',
    status: 'in_progress',
    priority: 'urgent',
    kind: 'recruiting_action',
    domainRootId: 'recruiting',
    menuContextId: 'vacancies-list',
    menuContextLabel: 'Вакансии',
    dueDate: '2026-04-02',
    startDate: '2026-03-28',
    assignee: 'Голубенко А.',
    sourceSystem: 'ATS',
    tags: ['оффер', 'согласование', 'вилка'],
    primaryLink: { label: 'Вакансии', href: '/vacancies' },
    links: [
      { label: 'Карточка в ATS', href: '/ats/vacancy/1/candidate/1' },
      { label: 'Бенчмарки', href: '/company-settings/finance/benchmarks' },
      { label: 'Шаблон оффера', href: '/company-settings/recruiting/offer-template' },
    ],
  },
  {
    id: 't-rec-2',
    title: 'Проверить заявку на найм: Support Engineer',
    summary: 'Уточнить SLA и приоритет с заказчиком; при необходимости обновить план найма.',
    status: 'open',
    priority: 'high',
    kind: 'recruiting_action',
    domainRootId: 'recruiting',
    menuContextId: 'vacancies-requests',
    menuContextLabel: 'Заявки на найм',
    dueDate: '2026-03-31',
    assignee: 'Черномордин А.',
    sourceSystem: 'Hiring plan',
    tags: ['заявка', 'SLA'],
    primaryLink: { label: 'Заявки на найм', href: '/hiring-requests' },
    links: [
      { label: 'План найма', href: '/reporting/hiring-plan' },
      { label: 'SLA вакансий', href: '/company-settings/sla' },
    ],
    moduleRiskHint: 'При отключении модуля «Рекрутинг» виджеты плана найма и отчёты по подбору могут стать недоступны.',
  },
  {
    id: 't-rec-3',
    title: 'Завершить оценку по инвайту (скрининг)',
    summary: 'Заполнить форму интервью и зафиксировать решение по кандидату.',
    status: 'in_progress',
    priority: 'medium',
    kind: 'recruiting_action',
    domainRootId: 'recruiting',
    menuContextId: 'invites',
    menuContextLabel: 'Интервью и скрининги',
    dueDate: '2026-03-30',
    assignee: 'Голубенко А.',
    tags: ['инвайт', 'скрининг'],
    primaryLink: { label: 'Инвайты', href: '/invites' },
    links: [{ label: 'Ответы кандидатам', href: '/candidate-responses' }],
  },
  {
    id: 't-cal-1',
    title: 'Подтвердить слоты интервью на неделю',
    summary: 'Синхронизировать календарь с Huntflow и уведомить участников.',
    status: 'open',
    priority: 'high',
    kind: 'meeting_followup',
    domainRootId: 'calendar',
    menuContextLabel: 'Календарь',
    dueDate: '2026-03-31',
    assignee: 'Голубенко А.',
    sourceSystem: 'Calendar',
    tags: ['интервью', 'слоты'],
    primaryLink: { label: 'Календарь', href: '/calendar' },
    links: [
      { label: 'Настройки календаря', href: '/calendar/settings' },
      { label: 'Интервьюеры', href: '/interviewers' },
    ],
    moduleRiskHint: 'Собеседования из рекрутинга создают события в календаре — проверьте доступность модуля.',
  },
  {
    id: 't-wf-1',
    title: 'Ответить в Inbox по вакансии Backend',
    summary: 'Суммаризировать статус воронки и следующие шаги для заказчика.',
    status: 'in_progress',
    priority: 'medium',
    kind: 'workflow_inbox',
    domainRootId: 'workflow-chat',
    menuContextLabel: 'Workflow chat',
    dueDate: '2026-04-01',
    assignee: 'Голубенко А.',
    tags: ['inbox', 'коммуникация'],
    primaryLink: { label: 'Inbox / Workflow', href: '/workflow' },
    links: [{ label: 'AI Chat', href: '/aichat' }],
  },
  {
    id: 't-task-1',
    title: 'Разобрать очередь «Мои задачи»',
    summary: 'Приоритизировать пункты из трея и связать с доменами (рекрутинг / HROps).',
    status: 'open',
    priority: 'low',
    kind: 'workflow_inbox',
    domainRootId: 'tasks',
    menuContextLabel: 'Задачи',
    dueDate: '2026-04-05',
    assignee: 'Голубенко А.',
    tags: ['обзор', 'приоритеты'],
    primaryLink: { label: 'Текущая страница', href: '/tasks' },
    links: [{ label: 'Профиль — быстрые кнопки', href: '/account/profile?tab=quick-buttons' }],
  },
  {
    id: 't-onb-1',
    title: 'Проверить чек-лист онбординга (неделя 1)',
    summary: 'Отметить выполненные пункты и эскалировать блокеры в HROps.',
    status: 'in_progress',
    priority: 'medium',
    kind: 'hr_ops',
    domainRootId: 'onboarding',
    menuContextId: 'onboarding-checklists',
    menuContextLabel: 'Чек-листы',
    dueDate: '2026-04-03',
    assignee: 'HR BP',
    tags: ['онбординг', 'чек-лист'],
    primaryLink: { label: 'Онбординг (раздел)', href: '/onboarding' },
    links: [{ label: 'HROps — документы', href: '/hr-services/documents' }],
    moduleRiskHint: 'HROps содержит ссылки на онбординг — при отключении онбординга проверьте сценарии ДО.',
  },
  {
    id: 't-hr-1',
    title: 'Согласовать заявку на отпуск',
    summary: 'Проверить пересечения с проектами и аллокацией.',
    status: 'open',
    priority: 'medium',
    kind: 'approval',
    domainRootId: 'hr-services',
    menuContextId: 'hr-services-leave',
    menuContextLabel: 'Отпуска',
    dueDate: '2026-04-04',
    assignee: 'Руководитель',
    tags: ['отпуск', 'согласование'],
    primaryLink: { label: 'HROps — отпуска', href: '/hr-services/leave' },
    links: [{ label: 'Ресурсы проектов', href: '/projects/resources' }],
  },
  {
    id: 't-er-1',
    title: 'Обновить матрицу грейдов Frontend',
    summary: 'Согласовать изменения с рекрутингом и отразить в специализациях.',
    status: 'blocked',
    priority: 'high',
    kind: 'project',
    domainRootId: 'employee-relations',
    menuContextId: 'specializations-all',
    menuContextLabel: 'Специализации',
    dueDate: '2026-04-10',
    assignee: 'HR BP',
    tags: ['грейды', 'матрица'],
    primaryLink: { label: 'Специализации', href: '/specializations' },
    links: [
      { label: 'Грейды компании', href: '/company-settings/grades' },
      { label: 'Вакансии', href: '/vacancies' },
    ],
  },
  {
    id: 't-learn-1',
    title: 'Назначить курс по ИБ новым сотрудникам',
    summary: 'Пакетное назначение + дедлайн прохождения.',
    status: 'open',
    priority: 'low',
    kind: 'learning',
    domainRootId: 'learning',
    menuContextId: 'learning-courses',
    menuContextLabel: 'Курсы',
    dueDate: '2026-04-15',
    assignee: 'L&D',
    tags: ['обучение', 'ИБ'],
    primaryLink: { label: 'L&D — курсы', href: '/learning/courses' },
    links: [{ label: 'Отчётность L&D', href: '/learning/reports' }],
  },
  {
    id: 't-perf-1',
    title: 'Подготовить калибровку Q2 (nine-box)',
    summary: 'Собрать данные по командам и зафиксировать дату сессии.',
    status: 'in_progress',
    priority: 'high',
    kind: 'meeting_followup',
    domainRootId: 'performance',
    menuContextId: 'performance-ninebox',
    menuContextLabel: 'Nine-box',
    dueDate: '2026-04-08',
    assignee: 'HR BP',
    tags: ['калибровка', 'nine-box'],
    primaryLink: { label: 'Nine-box', href: '/performance/ninebox' },
    links: [{ label: 'Шкалы оценок', href: '/company-settings/rating-scales' }],
  },
  {
    id: 't-fin-1',
    title: 'Проверить актуальность вилки для Middle Data',
    summary: 'Сверка с бенчмарками и внутренними диапазонами.',
    status: 'open',
    priority: 'medium',
    kind: 'analytics',
    domainRootId: 'finance',
    menuContextId: 'finance-salary-ranges',
    menuContextLabel: 'Зарплатные вилки',
    dueDate: '2026-04-06',
    assignee: 'C&B',
    tags: ['вилки', 'бенчмарки'],
    primaryLink: { label: 'Зарплатные вилки', href: '/vacancies/salary-ranges' },
    links: [{ label: 'Бенчмарки — обзор', href: '/finance/benchmarks' }],
  },
  {
    id: 't-hrpr-1',
    title: 'Опубликовать пост на внутреннем сайте',
    summary: 'Согласовать текст с PR и выложить в раздел новостей.',
    status: 'delegated',
    priority: 'medium',
    kind: 'communication',
    domainRootId: 'hr-pr',
    menuContextLabel: 'Внутренний сайт',
    dueDate: '2026-04-07',
    assignee: 'HR PR',
    tags: ['коммуникации', 'пост'],
    primaryLink: { label: 'Внутренний сайт', href: '/internal-site' },
    links: [
      { label: 'Wiki', href: '/wiki' },
      { label: 'База знаний (новый)', href: '/wiki-new' },
    ],
  },
  {
    id: 't-proj-1',
    title: 'Синк по аллокации на квартал',
    summary: 'Согласовать FTE с владельцами продуктов; обновить проектную карточку.',
    status: 'in_progress',
    priority: 'medium',
    kind: 'project',
    domainRootId: 'projects',
    menuContextId: 'projects-resources',
    menuContextLabel: 'Ресурсы',
    dueDate: '2026-04-09',
    assignee: 'PMO',
    tags: ['аллокация', 'FTE'],
    primaryLink: { label: 'Ресурсы и аллокация', href: '/projects/resources' },
    links: [
      { label: 'Команды проектов', href: '/projects/teams' },
      { label: 'Проекты', href: '/projects' },
    ],
  },
  {
    id: 't-an-1',
    title: 'Выгрузить сводный отчёт по подбору за месяц',
    summary: 'Для руководства: воронка, T2H, источники.',
    status: 'open',
    priority: 'low',
    kind: 'analytics',
    domainRootId: 'analytics',
    menuContextLabel: 'Отчётность',
    dueDate: '2026-04-12',
    assignee: 'Аналитик HR',
    tags: ['отчёт', 'рекрутинг'],
    primaryLink: { label: 'Отчётность', href: '/reporting' },
    links: [
      { label: 'План найма (год)', href: '/reporting/hiring-plan/yearly' },
      { label: 'Отчёт по компании', href: '/reporting/company' },
    ],
  },
  {
    id: 't-int-1',
    title: 'Проверить webhook n8n после обновления',
    summary: 'Тестовая доставка событий candidate.updated; проверить подпись.',
    status: 'open',
    priority: 'high',
    kind: 'integration',
    domainRootId: 'integrations',
    menuContextId: 'integrations-n8n',
    menuContextLabel: 'n8n',
    dueDate: '2026-03-29',
    assignee: 'DevOps / HRIS',
    sourceSystem: 'n8n',
    tags: ['webhook', 'автоматизация'],
    primaryLink: { label: 'Исходящие API и вебхуки', href: '/company-settings/system/outbound' },
    links: [
      { label: 'n8n (интеграции)', href: '/integrations/n8n' },
      { label: 'Интеграции компании', href: '/company-settings/integrations' },
      { label: 'Telegram', href: '/telegram' },
    ],
  },
  {
    id: 't-set-1',
    title: 'Актуализировать включённые модули в навигации',
    summary: 'Сверить дерево модулей с политикой доступа; задокументировать отключения.',
    status: 'open',
    priority: 'medium',
    kind: 'settings',
    domainRootId: 'settings',
    menuContextLabel: 'Настройки',
    dueDate: '2026-04-11',
    assignee: 'Администратор',
    tags: ['модули', 'доступ'],
    primaryLink: { label: 'Модули (вкл/выкл)', href: '/settings/modules' },
    links: [
      { label: 'Локализация', href: '/company-settings/system/localization' },
      { label: 'Группы пользователей', href: '/company-settings/user-groups' },
    ],
    moduleRiskHint: 'Корневые пункты «Задачи», «Аналитика», «Интеграции» в настройках модулей заблокированы от выключения.',
  },
]
