import type { Vacancy } from './types'

export const mockVacancies: Vacancy[] = [
  {
    id: 4090046,
    title: 'AQA Engineer (TS)',
    status: 'inactive',
    recruiter: 'Andrei Golubenko',
    locations: ['Минск', 'Удалённо'],
    interviewers: 0,
    date: '25.10.2025',
    hasWarning: true,
    warningText: 'Зарплатные вилки не установлены',
  },
  {
    id: 3993218,
    title: 'UX/UI Designer',
    status: 'inactive',
    recruiter: 'Andrei Golubenko',
    locations: [],
    interviewers: 0,
    date: '22.09.2025',
    hasWarning: true,
    warningText: 'Зарплатные вилки не установлены',
  },
  {
    id: 4020335,
    title: 'System Administrator',
    status: 'inactive',
    recruiter: 'Andrei Golubenko',
    locations: ['Гомель'],
    interviewers: 0,
    date: '22.09.2025',
    hasWarning: true,
    warningText: 'Зарплатные вилки не установлены',
  },
  {
    id: 4092269,
    title: 'Manual QA Engineer',
    status: 'inactive',
    recruiter: 'Andrei Golubenko',
    locations: [],
    interviewers: 0,
    date: null,
    hasWarning: false,
  },
  {
    id: 3979419,
    title: 'DevOps Engineer',
    status: 'inactive',
    recruiter: 'Andrei Golubenko',
    locations: ['Минск', 'Удалённо', 'Польша'],
    interviewers: 0,
    date: null,
    hasWarning: false,
  },
  {
    id: 3936534,
    title: 'Project Manager',
    status: 'active',
    recruiter: 'Andrei Golubenko',
    locations: ['Минск'],
    interviewers: 2,
    date: null,
    hasWarning: false,
  },
  {
    id: 4090047,
    title: 'Frontend Engineer',
    status: 'active',
    recruiter: 'Andrei Golubenko',
    locations: ['Минск', 'Удалённо'],
    interviewers: 1,
    date: '26.10.2025',
    hasWarning: false,
  },
  {
    id: 4090048,
    title: 'Backend Engineer',
    status: 'inactive',
    recruiter: 'Andrei Golubenko',
    locations: ['Варшава', 'Удалённо'],
    interviewers: 0,
    date: '20.10.2025',
    hasWarning: true,
    warningText: 'Зарплатные вилки не установлены',
  },
]

