import type { HiringRequest } from './types'

export const MOCK_REQUESTS: HiringRequest[] = [
  {
    id: 1001,
    title: 'Frontend Engineer (React)',
    grade: 'Middle',
    project: 'PUI Skins',
    recruiter: 'Golubenko A.',
    recruiterDays: 27,
    status: 'in_process',
    startDate: '17.12.2025',
    endDate: '21.01.2026',
    isOverdue: false,
    factDays: 26,
    slaDays: 35,
    slaStatus: 'normal',
    t2hSlaDays: 48,
    department: 'Разработка',
    priority: 'high',
    technologies: ['React', 'TypeScript', 'Next.js'],
    candidates: 5,
    date: '25.10.2025',
    hasWarning: false,
  },
  {
    id: 1002,
    title: 'Support Engineer (Service ...)',
    grade: 'Junior+',
    project: null,
    recruiter: 'Chernomordin A.',
    recruiterDays: 21,
    status: 'in_process',
    startDate: '15.12.2025',
    endDate: '14.01.2026',
    isOverdue: false,
    factDays: 28,
    slaDays: 30,
    slaStatus: 'risk',
    t2hSlaDays: 38,
    department: 'Поддержка',
    priority: 'medium',
    technologies: [],
    candidates: 0,
    date: '22.09.2025',
    hasWarning: false,
  },
  {
    id: 1003,
    title: 'DevOps Engineer',
    grade: 'Middle+',
    project: null,
    recruiter: 'Golubenko A.',
    recruiterDays: 32,
    status: 'closed',
    statusDate: '06.01.2026',
    startDate: '11.12.2025',
    endDate: '20.01.2026',
    isOverdue: false,
    factDays: 26,
    slaDays: 40,
    slaStatus: 'on_time',
    t2hDays: 67,
    t2hSlaDays: 56,
    candidate: { name: 'Aleksander Volvachev', id: '76779160' },
    department: 'Инфраструктура',
    priority: 'high',
    technologies: ['Docker', 'Kubernetes', 'AWS'],
    candidates: 1,
    date: '20.09.2025',
    hasWarning: false,
  },
  {
    id: 1004,
    title: 'Frontend Engineer (React)',
    grade: 'Junior+',
    project: 'PUI Skins',
    recruiter: 'Golubenko A.',
    recruiterDays: 33,
    status: 'in_process',
    startDate: '10.12.2025',
    endDate: '09.01.2026',
    isOverdue: true,
    factDays: 33,
    slaDays: 30,
    slaStatus: 'overdue',
    t2hSlaDays: 38,
    department: 'Разработка',
    priority: 'high',
    technologies: ['React', 'TypeScript'],
    candidates: 0,
    date: '18.09.2025',
    hasWarning: false,
  },
  {
    id: 1005,
    title: 'Backend Engineer',
    status: 'planned',
    statusDate: '01.02.2026',
    grade: 'Middle',
    project: null,
    recruiter: 'Andrei Golubenko',
    recruiterDays: 15,
    startDate: '01.12.2025',
    endDate: '15.01.2026',
    isOverdue: false,
    factDays: 20,
    slaDays: 35,
    slaStatus: 'normal',
    t2hSlaDays: 38,
    department: 'Разработка',
    priority: 'medium',
    technologies: ['Python', 'Django', 'PostgreSQL'],
    candidates: 3,
    date: '22.09.2025',
    hasWarning: false,
  },
]

