import type { CodingLanguageDefinition } from './types'

/** Полный каталог: вариативность стеков, как в симуляторах вроде Meet2Code. */
export const CODING_LANGUAGE_CATALOG: CodingLanguageDefinition[] = [
  {
    id: 'html',
    title: 'HTML',
    description:
      'Разметка документа, семантика, доступность. В паре с CSS и JS даёт полный предпросмотр в браузере.',
    previewKind: 'web',
    category: 'markup',
    runner: 'iframe-web',
    relatedIds: ['css', 'js'],
    order: 10,
  },
  {
    id: 'css',
    title: 'CSS',
    description: 'Каскад, адаптив, переменные, flex/grid. Живой превью в веб-песочнице.',
    previewKind: 'styles',
    category: 'styles',
    runner: 'iframe-web',
    relatedIds: ['html', 'js'],
    order: 20,
  },
  {
    id: 'js',
    title: 'JavaScript',
    description: 'Логика в браузере и основа для Node. Универсальная точка для фронта и скриптов.',
    previewKind: 'web',
    category: 'language',
    runner: 'iframe-web',
    relatedIds: ['html', 'css', 'ts', 'node', 'react'],
    order: 30,
  },
  {
    id: 'ts',
    title: 'TypeScript',
    description:
      'Статическая типизация поверх JS. В песочнице — редактор и сценарий компиляции; запуск через сборку или API.',
    previewKind: 'compile',
    category: 'language',
    runner: 'typescript-note',
    relatedIds: ['js', 'react'],
    order: 40,
  },
  {
    id: 'react',
    title: 'React',
    description:
      'Компонентный UI. Полный JSX — CDN/importmap или бандлер; базовые демо — HTML+JS в iframe.',
    previewKind: 'web',
    category: 'framework',
    runner: 'iframe-web',
    relatedIds: ['js', 'ts', 'html', 'css'],
    order: 50,
  },
  {
    id: 'node',
    title: 'Node.js',
    description: 'Серверный рантайм JavaScript, npm, сборка. Исполнение — на бэкенде (мок в UI).',
    previewKind: 'runtime',
    category: 'runtime',
    runner: 'server-mock',
    relatedIds: ['js', 'ts'],
    order: 60,
  },
  {
    id: 'python',
    title: 'Python',
    description:
      'Скрипты и алгоритмы, типичный live coding на собесах. Запуск — изолированный воркер/сервер.',
    previewKind: 'runtime',
    category: 'language',
    runner: 'server-mock',
    relatedIds: ['node', 'sql'],
    order: 70,
  },
  {
    id: 'go',
    title: 'Go',
    description: 'Системный и серверный стек. Исполнение вне браузера.',
    previewKind: 'runtime',
    category: 'systems',
    runner: 'server-mock',
    relatedIds: ['node', 'rust'],
    order: 80,
  },
  {
    id: 'rust',
    title: 'Rust',
    description: 'Память без GC, безопасность и скорость. Задачи на низкий уровень.',
    previewKind: 'compile',
    category: 'systems',
    runner: 'server-mock',
    relatedIds: ['go', 'js'],
    order: 90,
  },
  {
    id: 'sql',
    title: 'SQL',
    description: 'Запросы к БД. Проверка — бэкенд или WASM-SQLite (позже).',
    previewKind: 'runtime',
    category: 'data',
    runner: 'static-only',
    relatedIds: ['node', 'python'],
    order: 100,
  },
  {
    id: 'json',
    title: 'JSON / YAML',
    description: 'Конфиги и обмен данными. Валидация и подсветка без исполнения.',
    previewKind: 'compile',
    category: 'data',
    runner: 'static-only',
    relatedIds: ['js', 'node'],
    order: 110,
  },
  {
    id: 'vue',
    title: 'Vue',
    description: 'Прогрессивный UI-фреймворк. В песочнице — текстовый слот; полный SFC — через сборку.',
    previewKind: 'web',
    category: 'framework',
    runner: 'server-mock',
    relatedIds: ['js', 'ts', 'html', 'css'],
    order: 115,
  },
  {
    id: 'svelte',
    title: 'Svelte',
    description: 'Компилятор в императивный DOM. Мок-раннер; для live — bundler или REPL.',
    previewKind: 'compile',
    category: 'framework',
    runner: 'server-mock',
    relatedIds: ['js', 'ts'],
    order: 116,
  },
  {
    id: 'angular',
    title: 'Angular',
    description: 'Платформа на TypeScript: модули, DI, RxJS. Исполнение вне браузерной песочницы (мок).',
    previewKind: 'compile',
    category: 'framework',
    runner: 'server-mock',
    relatedIds: ['ts', 'html', 'css'],
    order: 117,
  },
  {
    id: 'java',
    title: 'Java',
    description: 'JVM, Spring, алгоритмы на собесах. Запуск — сервер/IDE (мок в UI).',
    previewKind: 'runtime',
    category: 'language',
    runner: 'server-mock',
    relatedIds: ['kotlin', 'node', 'sql'],
    order: 118,
  },
  {
    id: 'kotlin',
    title: 'Kotlin',
    description: 'JVM и multiplatform. Часто в паре с Java/Android.',
    previewKind: 'compile',
    category: 'language',
    runner: 'server-mock',
    relatedIds: ['java', 'ts'],
    order: 119,
  },
  {
    id: 'csharp',
    title: 'C#',
    description: '.NET, ASP.NET, Unity-подмножество. Рантайн в песочнице — мок.',
    previewKind: 'runtime',
    category: 'language',
    runner: 'server-mock',
    relatedIds: ['node', 'ts'],
    order: 120,
  },
  {
    id: 'php',
    title: 'PHP',
    description: 'Серверный web-классика. В моке — вывод как у Node/Python.',
    previewKind: 'runtime',
    category: 'language',
    runner: 'server-mock',
    relatedIds: ['node', 'sql'],
    order: 121,
  },
  {
    id: 'ruby',
    title: 'Ruby',
    description: 'Rails и скрипты. Исполнение вне браузера (мок).',
    previewKind: 'runtime',
    category: 'language',
    runner: 'server-mock',
    relatedIds: ['node', 'sql'],
    order: 122,
  },
  {
    id: 'bash',
    title: 'Bash',
    description: 'Shell, CI/CD, DevOps-сценарии. Без реального sh в iframe.',
    previewKind: 'runtime',
    category: 'runtime',
    runner: 'server-mock',
    relatedIds: ['node', 'python', 'docker'],
    order: 123,
  },
  {
    id: 'cpp',
    title: 'C++',
    description: 'Системное программирование, STL. Компиляция — мок.',
    previewKind: 'compile',
    category: 'systems',
    runner: 'server-mock',
    relatedIds: ['rust', 'c', 'go'],
    order: 124,
  },
  {
    id: 'c',
    title: 'C',
    description: 'Низкоуровневый код, алгоритмы, встраиваемые задачи.',
    previewKind: 'compile',
    category: 'systems',
    runner: 'server-mock',
    relatedIds: ['cpp', 'rust'],
    order: 125,
  },
  {
    id: 'swift',
    title: 'Swift',
    description: 'iOS/macOS, серверный Swift. Рантайм в браузере не эмулируем (мок).',
    previewKind: 'compile',
    category: 'language',
    runner: 'server-mock',
    relatedIds: ['ts', 'kotlin'],
    order: 126,
  },
  {
    id: 'dart',
    title: 'Dart',
    description: 'Flutter и AOT. Редактор и мок-раннер для сниппетов.',
    previewKind: 'compile',
    category: 'language',
    runner: 'server-mock',
    relatedIds: ['js', 'ts'],
    order: 127,
  },
  {
    id: 'docker',
    title: 'Dockerfile',
    description: 'Образы и multi-stage build. Статическая проверка и подсветка (мок).',
    previewKind: 'compile',
    category: 'systems',
    runner: 'static-only',
    relatedIds: ['node', 'bash'],
    order: 128,
  },
  {
    id: 'markdown',
    title: 'Markdown',
    description: 'Документация, README, ADR. Без исполнения.',
    previewKind: 'compile',
    category: 'data',
    runner: 'static-only',
    relatedIds: ['html', 'json'],
    order: 129,
  },
]

export function getLanguageById(id: string): CodingLanguageDefinition | undefined {
  return CODING_LANGUAGE_CATALOG.find((l) => l.id === id)
}

export function sortCatalog(list: CodingLanguageDefinition[]): CodingLanguageDefinition[] {
  return [...list].sort((a, b) => a.order - b.order)
}
