/** Стартовые сниппеты для моноредакторов (мок), по id языка каталога. */
export const PLAYGROUND_MONO_DEFAULTS: Record<string, string> = {
  node: `// Node.js (мок — исполнение на сервере)\nconsole.log('npm run dev');`,
  python: `def greet(name: str) -> str:\n    return f"Hello, {name}!"\n\nprint(greet("Meet2Code"))`,
  go: `package main\nimport "fmt"\nfunc main() {\n  fmt.Println("Hello, Go")\n}`,
  rust: `fn main() {\n    println!("Hello, Rust");\n}`,
  sql: `SELECT id, title\nFROM tasks\nWHERE status = 'open'\nLIMIT 5;`,
  json: `{\n  "task": "frontend-interview",\n  "languages": ["ts", "react"],\n  "sandbox": true\n}`,
  ts: `type User = { id: string; name: string };\nconst u: User = { id: '1', name: 'Анна' };\nconsole.log(u.name);`,
  react: `// Слот React: в моке код склеивается с JS и выполняется в iframe (без CDN React)\nconsole.log('[React] подключите react+react-dom для JSX');`,
  vue: `<template>\n  <p>{{ message }}</p>\n</template>\n<script setup>\nconst message = 'Vue (текст в моке)'\n</script>`,
  svelte: `<script>\n  let name = 'Svelte';\n</script>\n<h1>Hello {name}</h1>`,
  angular: `import { Component } from '@angular/core';\n@Component({\n  selector: 'app-root',\n  template: '<p>{{ title }}</p>',\n})\nexport class AppComponent { title = 'Angular мок'; }`,
  java: `public class Main {\n  public static void main(String[] args) {\n    System.out.println("Hello, Java");\n  }\n}`,
  kotlin: `fun main() {\n    println("Hello, Kotlin")\n}`,
  csharp: `class Program {\n  static void Main() {\n    System.Console.WriteLine("Hello, C#");\n  }\n}`,
  php: `<?php\necho "Hello, PHP\\n";`,
  ruby: `def greet(name)\n  "Hello, #{name}"\nend\nputs greet("Ruby")`,
  bash: `#!/usr/bin/env bash\nset -euo pipefail\necho "Hello, Bash"`,
  cpp: `#include <iostream>\nint main() {\n  std::cout << "Hello, C++" << std::endl;\n  return 0;\n}`,
  c: `#include <stdio.h>\nint main(void) {\n  printf("Hello, C\\n");\n  return 0;\n}`,
  swift: `print("Hello, Swift")`,
  dart: `void main() {\n  print('Hello, Dart');\n}`,
  docker: `FROM node:20-alpine\nWORKDIR /app\nCOPY . .\nRUN npm ci\nCMD ["node", "index.js"]`,
  markdown: `# Заметка\n\n- пункт\n- **жирный**\n\n\`\`\`ts\nconst x = 1\n\`\`\``,
}
